apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.headscaleui.name }}-deployment
  labels:
    app: {{ .Values.headscaleui.name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.headscaleui.name }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.headscaleui.name }}-app
    spec:
      {{- if .Values.headscaleui.volumes }}
      volumes: 
      {{- range .Values.headscaleui.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .pvcName}}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Values.headscaleui.name }}-app
          image: {{ .Values.headscaleui.image }}
          {{- if .Values.headscaleui.volumes }}
          volumeMounts:
          {{- range .Values.headscaleui.volumes }}
            - name: "{{ .name }}"
              mountPath: "{{ .mountPath }}"
              subPath: "{{ .subPath }}"
          {{- end }}
          {{- if .Values.headscaleui.usb }}
          {{- range .Values.headscaleui.usb }}
            - name: "{{.name}}"
              mountPath: "{{.mountPath}}"
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if .Values.headscaleui.commands }}
          args: {{ toYaml .Values.headscaleui.commands | nindent 12 }}
          {{- end }}
          {{- if .Values.headscaleui.args }}
          args: {{ toYaml .Values.headscaleui.args | nindent 12 }}
          {{- end }}
          {{- if .Values.headscaleui.env }}
          env:
          {{- range .Values.headscaleui.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
          {{- end }}
          {{- end }}
          {{- if .Values.headscaleui.secret }}
          {{- if .Values.headscaleui.secret.enable }}
          envFrom:
            - secretRef:
                name: {{ .Values.headscaleui.secret.name }}
          {{- end }}
          {{- end }}
          {{- if .Values.headscaleui.ports }}
          ports:
          {{- range .Values.headscaleui.ports }}
            - name: {{ .portName }}
              containerPort: {{ .targetPort }}
          {{- end }}
          {{- end }}
          
          {{- if .Values.headscaleui.readinessProbe }}
          readinessProbe: {{ toYaml .Values.headscaleui.readinessProbe | nindent 12 }}
          {{- end }}