{{- range Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment
  labels:
    app: {{ .name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}-app
  template:
    metadata:
      labels:
        app: {{ .name }}-app
    spec:
      {{- if .volumes }}
      volumes: 
      {{- range .volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .pvcName}}
      {{- end }}
      {{- end }}
      {{- if .usb }}
      {{- range .usb }}
        - name: "{{.name}}"
          hostPath:
            path: "{{.mountPath}}"
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .name }}-app
          image: {{ .image }}
          {{- if .volumes }}
          volumeMounts:
          {{- range .volumes }}
            - name: "{{ .name }}"
              mountPath: "{{ .mountPath }}"
              subPath: "{{ .subPath }}"
          {{- end }}
          {{- if .usb }}
          {{- range .usb }}
            - name: "{{.name}}"
              mountPath: "{{.mountPath}}"
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if .commands }}
          args: {{ toYaml .commands | nindent 12 }}
          {{- end }}
          {{- if .args }}
          args: {{ toYaml .args | nindent 12 }}
          {{- end }}
          {{- if .env }}
          env:
          {{- range .env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
          {{- end }}
          {{- end }}
          {{- if .secret }}
          {{- if .secret.enable }}
          envFrom:
            - secretRef:
                name: {{ .secret.name }}
          {{- end }}
          {{- end }}
          {{- if .Values.service.ports }}
          ports:
          {{- range .Values.service.ports }}
            - name: {{ .portName }}
              containerPort: {{ .targetPort }}
          {{- end }}
          {{- end }}
          
          {{- if .readinessProbe }}
          readinessProbe: {{ toYaml .readinessProbe | nindent 12 }}
          {{- end }}
{{- end }}