{{- range .Values.apps }}
{{- if .ingress }}
{{- if .ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    cert-manager.io/issuer: lets-encrypt
    {{ range .ingress.annotations }}
      {{- .}}
    {{- end }}

spec:
  template:
    metadata:
      labels:
        app: {{ .name }}-service
  tls:
  - hosts:
    {{- range .ingress.hosts }}
    - {{ . }}
    {{- end}}
    secretName: {{ .name }}-ingress-tls
  rules:
  # add a rule for each host
    {{- range .ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          {{- range $.service.ports }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.name }}-service
                port:
                  name: {{ .portName }}
          {{- end }}
    {{- end }}                  
{{- end }}                  
{{- end }}
{{- end }}
