{{- if .Values.postgres }}
{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name}}-service
spec:
  selector:
    app: {{ .Values.postgres.name}}-app
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name}}-app
  ports:
    {{- range .Values.postgres.ports }}
    - name: {{ .portName }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}-deployment
  labels:
    app: {{ .Values.postgres.name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}-app
    spec:
      {{- if .Values.postgres.volumes }}
      volumes: 
      {{- range .Values.postgres.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .pvcName}}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Values.postgres.name }}-app
          image: {{ .Values.postgres.image }}
          env:
          - name: "POSTGRES_DB"
            value: "{{ .Values.postgres.db }}"
          - name: POSTGRES_USER
            value: "{{ .Values.postgres.user }}"
          - name: POSTGRES_PASSWORD
            value: "{{ .Values.postgres.password }}"
          {{- range .Values.postgres.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
          {{- end }}
          {{- if .Values.postgres.volumes }}
          volumeMounts:
          {{- range .Values.postgres.volumes }}
            - name: "{{ .name }}"
              mountPath: "{{ .mountPath }}"
              subPath: "{{ .subPath }}"
          {{- end }}
          {{- end }}
          {{- if .Values.postgres.ports }}
          ports:
          {{- range .Values.postgres.ports }}
            - name: {{ .portName }}
              containerPort: {{ .targetPort }}
          {{- end }}
          {{- end }}
{{- end }}
{{- end }}
