{{- range .Values.apps }}
{{- if .service && .service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name}}-service
spec:
  selector:
    app: {{ .name}}-app
  template:
    metadata:
      labels:
        app: {{ .name}}-app
  ports:
    {{- range .service.ports }}
    - name: {{ .portName }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  type: ClusterIP
  {{- end }}
{{- end }}