apiVersion: v2
name: firefly-iii-stack
version: 0.7.2
description: Installs Firefly III stack (db, app, importer)
type: application
dependencies:
- name: firefly-db
  version: 0.2.1
  condition: firefly-db.enabled
  repository: file://../firefly-db
- name: firefly-iii
  version: 1.7.1
  condition: firefly-iii.enabled
  repository: file://../firefly-iii
- name: importer
  version: 1.3.1
  condition: importer.enabled
  repository: file://../importer