apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      volumes:
      {{- range .Values.app.volumes}}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .pvc }}
      {{- end }}
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          ports:
          {{- range .Values.app.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: TCP
          {{- end }}
          env:
            - name: DB_MYSQL_HOST
              value: "{{ .Values.app.env.DB_MYSQL_HOST }}"
            - name: DB_MYSQL_PORT
              value: "{{ .Values.app.env.DB_MYSQL_PORT }}"
            - name: DB_MYSQL_USER
              value: "{{ .Values.app.env.DB_MYSQL_USER }}"
            - name: DB_MYSQL_PASSWORD
              value: "{{ .Values.app.env.DB_MYSQL_PASSWORD }}"
            - name: DB_MYSQL_NAME
              value: "{{ .Values.app.env.DB_MYSQL_NAME }}"
          volumeMounts:
          {{- range .Values.app.volumes}}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
          {{- end }}
