apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      volumes:
        - name: {{ .Values.db.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.db.volume.pvc }}
      containers:
        - name: {{ .Values.db.name }}
          image: {{ .Values.db.image }}
          ports:
            - name: mysql
              containerPort: {{ .Values.db.port }}
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.db.env.MYSQL_ROOT_PASSWORD }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.db.env.MYSQL_DATABASE }}"
            - name: MYSQL_USER
              value: "{{ .Values.db.env.MYSQL_USER }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.db.env.MYSQL_PASSWORD }}"
          volumeMounts:
            - name: {{ .Values.db.volume.name }}
              mountPath: {{ .Values.db.volume.mountPath }}