apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
spec:
  type: ClusterIP
  ports:
  {{- if .Values.app.ports }}
  {{- range .Values.app.ports }}
    - name: {{ .portName }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
  {{- end }}
  selector:
    app: {{ .Values.app.name }}